[build]
builder = "DOCKERFILE"
dockerfilePath = "./apps/web/Dockerfile"
watchPaths = ["packages", "apps/web"]

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
