services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CRM
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg: {}


