[build]
builder = "DOCKERFILE"
dockerfilePath = "./apps/analytics-service/Dockerfile"
watchPaths = ["apps/analytics-service"]

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port 3002"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
